name: Image Resizer Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  image_resize_job:
    name: Image Resize Job
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: Install LibVips
       run: sudo apt install libvips-tools
     - name: resize jpeg images
       run:  vipsthumbnail ./HTC/protocols/MTM/media/*.jpeg --size 1300x2600 -o $(readlink -f "./HTC/protocols/MTM/media/new_images/%s.jpeg")
     - name: Commit
       uses: stefanzweifel/git-auto-commit-action@v5
       
