name: Image Resizer Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  image_resize_job:
    name: Image Resize Job
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
     - name: resize
       uses: sharadcodes/img-resizer@v1.1
       with:
         image-folder: 'HTC/protocols/MTM/media' # This is a Required field & this folder has original images
         new-resolution: '1300x2600' # This is Required field
         output-folder: "HTC/protocols/MTM/media/new_images" # This is Required field & this folder will be used to store resized images

